### PR TITLE
Conversion of the library to TypeScript

### PR DESCRIPTION
**Pull request by vladimirmoushkov**
Removed 'react-scripts' in place of web pack.
Use:
`npm run build:prod`
to produce ./lib/ npm pack able directory that includes javascript and type definitions.

Note there is a problem with the displaying of some to the inks:

> s.default is not a function...

### CODE REVIEW

**Comment by winhtaikaung** [comment]
Hi @vladimirmoushkov, 
Thank you .It was great help for me and really appreciated that you spend time on me to migrate to typescript. But there are some small glitches on missing files in your commit  demo.tsx and .env 
Please refer to following screenshots.
## demo.tsx missing
Screenshot from 2019-03-30 16-56-56
## .env missing


Thanks
Win

**Comment by vladimirmoushkov** [comment]
Hello,
Apology for being clutter here!

I have added a demo page for *npm run start* and empty .env file for *npm
run deploy. *If you like to run the latter you will need to fill the .env
file with npmjs registry creds and etc. Feel free to remove any
packages.json you won't find useful. I have copied these from another
project. The only one needed is build:lib and start.
Did also fix couple of import issues but tiny link seems is unable to
handle all of the links I'm trying, see the screenshot below:
[image: Screenshot 2019-03-30 at 18.45.35.png]

**Comment by winhtaikaung** [comment]
Hi @vladimirmoushkov, 💯 Thanks for prompt response. Really appreciate it. I will check it soon and will look into the issue .

Cheers
Win

**Comment by vladimirmoushkov** [comment]
Thank you Win Htaik Aung!

Any plans of dates for future release?

**Pull request merged**
