### PR TITLE
add twitter scrapper

### PR DESCRIPTION
**Pull request by sndsabin**
- add twitter scrapper

### CODE REVIEW

**Comment by winhtaikaung** [comment]
Hi @sndsabin  great effort on the Twitter URL :+1: , could you please provide screen shot of component with Twitter URL ?

**Comment by sndsabin** [comment]
sure, here you go.
twitter-small-card
twitter-large-card

**Comment by winhtaikaung** [comment]
Hi @sndsabin Could you pleas rebase with master ?

**Comment by sndsabin** [comment]
Hey @winhtaikaung, please review this.

**Pull request merged**
