### PR TITLE
add loadSecureUrls props to resolve mixed content issue

### PR DESCRIPTION
**Pull request by sndsabin**
for details, please refer to https://github.com/winhtaikaung/react-tiny-link/pull/45

### CODE REVIEW

**Comment by sndsabin** [comment]
Hey @winhtaikaung just wondering when this PR will be merged into master and released ? It kinda important because we have used this package and been receiving complain about app not being secure despite SSL certificate due to mixed content.

**Comment by winhtaikaung** [comment]
@add-contributors please add @sndsabin  for code and bug

**Comment by winhtaikaung** [comment]
> Hey @winhtaikaung just wondering when this PR will be merged into master and released ? It's kinda important because we have used this package and been receiving complain about app not being secure despite SSL certificate due to mixed content.

Yes I will release it by today and will let you know again

**Comment by winhtaikaung** [comment]
@all-contributors please add @sndsabin for code and bug

**Comment by winhtaikaung** [comment]
Hey @sndsabin your fixes has been released please use v3.3.1

https://www.npmjs.com/package/react-tiny-link

Thank you for your contribution

**Comment by sndsabin** [comment]
Thanks @winhtaikaung  :)

**Pull request merged**
