### PR TITLE
add cache system

### PR DESCRIPTION
**Pull request by kalimantos**
cache link results and add `noCache` param to bypass it. #86

### CODE REVIEW

**Comment by winhtaikaung** [comment]
Hi @kalimantos  Please Rebase the MR

**Comment by winhtaikaung** [comment]
and also @kalimantos  could you please also update the README with your new hooks and usage ? 
Thanks

**Comment by kalimantos** [comment]
ok, few minutes and i'll add them

**Comment by kalimantos** [comment]
how it looks to you now?

**Pull request merged**
