### PR TITLE
Add rule for BoardGameGeek.

### PR DESCRIPTION
**Pull request by lizlam**

### CODE REVIEW

**Comment by winhtaikaung** [comment]
Hey @lizlam  Great Work, One request from me, Could you please  provide example url of boardgameGeek ?

**Comment by lizlam** [comment]
@winhtaikaung Sure, here is an example: https://boardgamegeek.com/boardgame/262211/cloudspire
Let me know if you want me to add an example to your github page.

**Comment by winhtaikaung** [comment]
> @winhtaikaung Sure, here is an example: https://boardgamegeek.com/boardgame/262211/cloudspire
> Let me know if you want me to add an example to your github page.

Hi @lizlam It would be great if you could provide :pray:

**Comment by lizlam** [comment]
@winhtaikaung Added an example to your demo page.  It looks like this:
bgg-example

**Comment by winhtaikaung** [comment]
Hi @lizlam  I will close this MR because I checkout your branch and resolve  conflicts  and merge on PR #66 .

Thanks for your contribution. :raised_hands:

**Comment by winhtaikaung** [comment]
@all-contributors please add @lizlam  for code example

**Pull request closed without merging**
