### PR TITLE
feat: export ScraperWraper

### PR DESCRIPTION
**Pull request by srghma**

### CODE REVIEW

**Comment by winhtaikaung** [comment]
Hi @srghma
May I know the reason of exporting the` Scrapper Wrapper ` please ?

**Comment by srghma** [comment]
Hi @winhtaikaung

I needed it in my project to use without react component

**Comment by winhtaikaung** [comment]
@all-contributors please add @srghma  for code bug

**Comment by winhtaikaung** [comment]
@all-contributors please add @srghma for code bug

**Pull request merged**
